### ISSUE TITLE
Canvas doubles size

### ISSUE THREAD

**Issue by josefheld** [michaeldzjap/react-signature-pad-wrapper#11]
When I developed an app with this package it looked fine until I ran it on my Macbook Pro.
Then the size of the canvas doubled in size. 
What causes this?

**Comment by michaeldzjap** [comment]
This has to do with the fact that on a macbook with a retina display `window.devicePixelRatio` (i.e. the ratio between physical pixels and device-independent pixels) is set to 2. This package takes this ratio into account when computing the actual dimensions of the canvas object to support HiDPI screens properly. See [this](https://www.html5rocks.com/en/tutorials/canvas/hidpi/) for more info.

**Comment by ustincameron** [comment]
Did you end up solving this? Package works great for my LG monitor but when on a Macbook Retina monitor the canvas is doubled in size and paint brush is not where mouse pointer is. Or how to resize by set height/width instead of percent would help deal with it a bit.
