### ISSUE TITLE
Production installs require `husky`

### ISSUE THREAD

**Issue by markrawls** [michaeldzjap/react-signature-pad-wrapper#29]
I see that `husky` is a dev dependency, but the `postinstall` hook runs after the package is installed in other projects. I'll open a PR to remove that line, but right now all installs of this package are broken for projects that do not use husky.

```
error /code/node_modules/react-signature-pad-wrapper: Command failed.
Exit code: 127
Command: husky install
Arguments: 
Directory: /code/node_modules/react-signature-pad-wrapper
Output:
/bin/sh: 1: husky: not found
info Visit <https://yarnpkg.com/en/docs/cli/install> for documentation about this command.
The command '/bin/sh -c yarn install' returned a non-zero code: 127
```

**Comment by michaeldzjap** [comment]
Good point. I merged your PR and do a new patch release tomorrow.
