### ISSUE TITLE
onEnd and onBegin doesn't not fire

### ISSUE THREAD

**Issue by ultrox** [michaeldzjap/react-signature-pad-wrapper#3]
I was trying to trigger some behaviour by passing function to onEnd hook, this hook dont want to fire. Am I doing something wrong? 

Basically I was trying to save the data to a state after user ends writing on the canvas.

  ```
function handleOnEnd() {
    console.log('never fire')
}
    <SignaturePad
        value={props.value}
        onEnd={handleOnEnd}
        ref={ref => (this.signaturePad = ref)}
        options={{}}
      />
```

**Comment by michaeldzjap** [comment]
@ultrox the `onEnd` and `onBegin` hooks are _signature_pad_ specific options. Hence, you need to specify them as part of the options property instead of having them as a direct property of the `SignaturePad` component. So this should do what you'd expect:
```javascript
function handleOnEnd() {
    console.log('never fire')
}
...
<SignaturePad
    ref={ref => (this.signaturePad = ref)}
    options={{onEnd: handleOnEnd}} />
```

**Comment by ultrox** [comment]
@michaeldzjap I though this might be it, but I end up assigning onEnd to instnace directly in lifecycle method, but I like your solution much better. Thanks Michael!

**Comment by shahriarhossain** [comment]
@michaeldzjap : 
I am calling the onEnd from within the options like this: 
![image](https://user-images.githubusercontent.com/6463320/213968708-38ea2355-7609-45c7-9f79-446a07563f13.png)

But for some reason its not getting triggered. 
I am using "react-signature-pad-wrapper": "^3.3.1"

**Comment by michaeldzjap** [comment]
@shahriarhossain  `onEnd` no longer exists in v4 of signature pad. See #36 and [this](https://github.com/szimek/signature_pad#events).
