### ISSUE TITLE
Expose underlying events from signature_pad

### ISSUE THREAD

**Issue by toburger** [michaeldzjap/react-signature-pad-wrapper#36]
Exposing the underlying events of `signature_pad` would be very useful as it allows to react to signature inputs instead of polling the data of `signature_pad`.

This would allow a pattern like:

```javascript
const [signature, setSignature] = useState("")
...
<SignaturePad ... onEnd={x=> setSignature(x.toDataURL())} />
```

or add the events to the options, as they are "low level" events, like

```javascript
<SignaturePad ... options={{
    onEnd(x) { setSignature(x.toDataURL()) }
}} />
```

This allows the rest of the code to react to the value of `signature` easily (e.g. disable the save button  and display a message if no signation was made...).

-----

Or alternatively expose the whole underying `signature_pad` object.

**Comment by michaeldzjap** [comment]
You can already get the original signature pad instance through a ref (e.g. see _Layout.tsx_ in the _example_ dir). I think that should allow you to do what you want?

**Comment by toburger** [comment]
Ah perfect! The `instance` field it is.. Thx!

**Comment by toburger** [comment]
If someone is having trouble accessing the underlying instance and registering the event with the hooks API here is the working TS code:

```typescript
  const [signaturePad, setSignaturePad] = React.useState<SignaturePad>();
  const signaturePadRef = React.useCallback((signaturePad: SignaturePad) => {
    setSignaturePad(signaturePad);
  }, []);
  React.useEffect(() => {
    if (signaturePad) {
      signaturePad.instance.onEnd = () => {
        setSignature(signaturePad.instance.toDataURL());
      };
    }
  }, [signaturePad]);
```

More info of why this is quite tricky can be found [here](https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node) or [here](https://medium.com/welldone-software/usecallback-might-be-what-you-meant-by-useref-useeffect-773bc0278ae).

**Comment by JamesRobertWiseman** [comment]
The above .onEnd no longer works as it was replaced by event emitters. [See here](https://github.com/szimek/signature_pad/pull/567)

The following updated code works: 
```javascript
  const [signaturePad, setSignaturePad] = React.useState<SignaturePad>();

  const signaturePadRef = React.useCallback((signaturePad: SignaturePad) => {
    setSignaturePad(signaturePad);
  }, []);

  React.useEffect(() => {
    if (signaturePad) {
      signaturePad.instance.addEventListener('endStroke', () => {
        setSignature(signaturePad.toDataURL());
      });
    }
  }, [signaturePad]);
```

**Comment by toburger** [comment]
Nice, thanks for the example!
I have to upgrade my code, but I suspect that it is necessary to remove the event listener in order to not reregister the event handler on every mount?

**Comment by JamesRobertWiseman** [comment]
You are right. The following will work:
```javascript 
  const [signaturePad, setSignaturePad] = React.useState<SignaturePad>();

  const signaturePadRef = React.useCallback((signaturePad: SignaturePad) => {
    setSignaturePad(signaturePad);
  }, []);

  const onStrokeEnd = () => {
    setSignature(signaturePad.toData());
  }

  React.useEffect(() => {
    if (signaturePad) {
      signaturePad.instance.addEventListener('endStroke', onStrokeEnd)
    }
    //cleanup event listener
    () => signaturePad.instance.removeEventListener('endStroke', onStrokeEnd);
  }, [signaturePad]);

```

**Comment by sankarkumar23** [comment]
> 

Have you tested the code?

**Comment by JamesRobertWiseman** [comment]
@sankarkumar23 Yes, and it is working fine my end.
