### ISSUE TITLE
Issue with source-map-loader - Failed to parse source map from 'XXX\node_modules\react-signature-pad-wrapper\src\SignaturePad.tsx'

### ISSUE THREAD

**Issue by cyrildurand** [michaeldzjap/react-signature-pad-wrapper#37]
I recently migrate my application to use react-scripts v5 and react-signature-pad-wrapper v3. Since then I have the following error message : 

> WARNING in ./node_modules/react-signature-pad-wrapper/dist/react-signature-pad-wrapper.es.js     
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'XX\node_modules\react-signature-pad-wrapper\src\SignaturePad.tsx' file: Error: ENOENT: no such file or directory, open 'XX\node_modules\react-signature-pad-wrapper\src\SignaturePad.tsx'

It looks that my build now look for source map. You npm package contains a `react-signature-pad-wrapper.js.map` that reference the source and the source code is not included in the package. 

Could you update the package to include source code ?

**Comment by michaeldzjap** [comment]
Ah, I see. I probably think it would be better to not include the source map files at all in the _npm_ distribution.

**Comment by cyrildurand** [comment]
it’s another solution that should work as well 😊

Thanks

**Comment by kenlyon** [comment]
What should be our course of action when using this component with typescript? The previous error was inconvenient, but the new version is not usable at all:
```
TS7016: Could not find a declaration file for module 'react-signature-pad-wrapper'. '<path>/node_modules/react-signature-pad-wrapper/dist/react-signature-pad-wrapper.js' 
implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-signature-pad-wrapper` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-signature-pad-wrapper';`
```
I tried adding `@types/react-signature-pad-wrapper` but that doesn't seem to exist.

**Comment by kenlyon** [comment]
Created #39 so this can be discussed separately.
