### ISSUE TITLE
Component no longer works with typescript since v3.1.0

### ISSUE THREAD

**Issue by kenlyon** [michaeldzjap/react-signature-pad-wrapper#39]
The removal of type information from the package means I can't import `"react-signature-pad-wrapper"` in a react project that uses typescript.

As a workaround I have copied the contents of `dist/SignaturePad.d.ts` from v3.0.0 into my own local `.d.ts` file, wrapped in `declare module "react-signature-pad-wrapper" { }`. This unblocks me for now, but it's not ideal as I don't want to maintain that separately.

I'd recommend you either reintroduce a `.d.ts` file in your project (addressing the issue of local paths that you just fixed in 3.1.0) or create a separate `@types/react-signature-pad-wrapper` project. Personally, I find it much more convenient when it's included in the library itself, but maybe typescript support isn't a priority.

**Comment by kenlyon** [comment]
While I'm on the subject, I noticed that [@types/signature_pad](https://www.npmjs.com/package/@types/signature_pad) is pretty out of date too. :(

**Comment by michaeldzjap** [comment]
Thanks for reporting this issue. I should have checked this more thoroughly before releasing, but I didn't...

Anyway, the problem seems to be the switch to the official rollup typescript plugin. It seems it doesn't [generate type declarations automatically](https://github.com/rollup/plugins/issues/61). I'll release a fix soon.

**Comment by michaeldzjap** [comment]
> While I'm on the subject, I noticed that [@types/signature_pad](https://www.npmjs.com/package/@types/signature_pad) is pretty out of date too. :(

This package doesn't use that. signature pad version 3 is rewritten in typescript, so doesn't need it either.

**Comment by michaeldzjap** [comment]
@kenlyon I just published v3.1.1 which includes the type declaration files again, so it should work again. Let me know if it doesn't.

**Comment by kenlyon** [comment]
Looks great now, thanks! Also good tip on the @types project. Once I removed it, I got the right types.
