### ISSUE TITLE
Running example

### ISSUE THREAD

**Issue by MiroslavPetrik** [michaeldzjap/react-signature-pad-wrapper#41]
The steps to run example are incomplete as the example is using the source of the lib, not the 'package'.
So the root directory must be build first, before the example dir.

**Comment by michaeldzjap** [comment]
I'm not quite sure what you mean by "_...the root directory must be build first, before the example dir._". Do you mean you have to install all example dependencies first before running `npm run build`?

**Comment by MiroslavPetrik** [comment]
The steps are

1. in the root run `npm install` 
2. then `cd example && npm install && npm run build`
3. open `example/index.html` in a browser of your choice.

**Comment by lpknv** [comment]
@michaeldzjap Is there a reason why not all the events aren't implemented? E.g. "endStroke", "beginStroke" etc? Or am I missing something?

**Comment by michaeldzjap** [comment]
@lpknv See the discussion for #36

**Comment by lpknv** [comment]
> @lpknv See the discussion for #36

Thank you for the clarification!
