### ISSUE TITLE
Signature with browser Zoom In and Zoom out

### ISSUE THREAD

**Issue by sankarkumar23** [michaeldzjap/react-signature-pad-wrapper#46]
I've implemented the signaturepad on react hooks. Everything working fine with default browser zoom 100%. I zoomed in the browser(say 80%), sign the signature and saved it. When I click on refresh/reload the signature the signature size is increasing to as if was signed with 100% zoom. Would there be a way keep the signature as per the current browser's zoom in/out size.
I tried redrawOnResize with true/false and also removing width & height.. but no difference.

`<SignaturePad ref={signaturePadRef} width={500} height={200} redrawOnResize={false} />`

Captured on browser with 80% zoom
![Signature](https://user-images.githubusercontent.com/12550023/167300203-95534431-142f-42af-9553-fd58f9eeb0a1.gif)

**Comment by michaeldzjap** [comment]
I don't think so. This package is merely a wrapper around [signature pad](https://github.com/szimek/signature_pad). Hence, all signature related drawing is offloaded to it. Maybe it would be possible to use 

```javascript
// Returns signature image as an array of point groups
const data = signaturePad.toData();
```

and [scale](https://www.geeksforgeeks.org/how-to-detect-page-zoom-level-in-all-modern-browsers-using-javascript/) the data points you get back by the appropriate zoom ratio and use

```javascript
// Draws signature image from an array of point groups
signaturePad.fromData(data);
```

to redraw the scaled signature. I have no idea if this would work, but this is what I would try out initially anyway. It's not something I'd build into this package though, as I feel it falls beyond the scope of what this package should do.
