### ISSUE TITLE
Signature Pad Flickering Issue

### ISSUE THREAD

**Issue by OpenxcellAbbas** [michaeldzjap/react-signature-pad-wrapper#56]
Hello,

I have been using your package in my product and recently updated my Chrome to Version 113.0.5672.126 and encountered this problem:

![Screenshot from 2023-05-29 11-11-48](https://github.com/michaeldzjap/react-signature-pad-wrapper/assets/134911032/14dec9c9-1777-41a3-a667-cc165ee0e27b)
The line flickers until you change the tab after which when you revisit it stops and displays only the last part of the stroke

Below is a screenshot for how it looked in Version 112.0.5615.121
![image_2023_05_29T05_45_45_715Z](https://github.com/michaeldzjap/react-signature-pad-wrapper/assets/134911032/28de6e50-76de-42ec-accf-14ff601b15fc)

**Comment by michaeldzjap** [comment]
I am pretty sure this is a problem with [signature pad](https://github.com/szimek/signature_pad), not this package. This is a simple _React_ wrapper around the linked repository. I would firstly look if you can find an open issue describing the same problem you are experiencing and if not, open a new issue in the issue tracker of that repository yourself.

Just had a look myself and [this](https://github.com/szimek/signature_pad/issues/718) seems to describe a similar problem. Maybe you can add your own findings to it as a comment.
