### ISSUE TITLE
Should we move throttle-debounce to dependencies?

### ISSUE THREAD

**Issue by phthhieu** [michaeldzjap/react-signature-pad-wrapper#60]
As throttle-debounce is used in production code https://github.com/michaeldzjap/react-signature-pad-wrapper/tree/8d362f5dfb550edbc119137515b0ab1d628ffda8/src/SignaturePad.tsx, should we move it to dependencies instead of devDependencies https://github.com/michaeldzjap/react-signature-pad-wrapper/blob/8d362f5dfb550edbc119137515b0ab1d628ffda8/package.json#L70

**Comment by michaeldzjap** [comment]
Yes, would be better to move it to dependencies.

**Comment by michaeldzjap** [comment]
Moved in [new release](https://github.com/michaeldzjap/react-signature-pad-wrapper/releases/tag/v3.4.0)
