### ISSUE TITLE
Save signature as svg or png

### ISSUE THREAD

**Issue by lylest** [michaeldzjap/react-signature-pad-wrapper#61]
This issue  raise the need to provide more documentation  and real world use case of saving the Generated signature into SVG or PNG, The current document documentation is very insufficient and does not well explain how to use this in real world solution, it is just a pieces of cropped code which does not do  a good job in explaining the actual usage, 
Please someone have a look at this

**Comment by michaeldzjap** [comment]
Thanks for raising this, but I don't think documenting this is something that this package should be responsible for to be honest. As you can see when you look at the example, [saving the image](https://github.com/michaeldzjap/react-signature-pad-wrapper/blob/8d362f5dfb550edbc119137515b0ab1d628ffda8/example/Layout.tsx#L37) (and generally any interaction with the signature data) is something that is completely offloaded to the underlying [signature pad](https://github.com/szimek/signature_pad?tab=readme-ov-file#api) instance. This package is merely a simple _React_ wrapper around the original signature pad package.

So I'd suggest perhaps raising an issue at the signature pad repository if you feel that documentation around the saving signature data to an image is unclear or insufficient.
