### ISSUE TITLE
`ref` is not a prop. 

### ISSUE THREAD

**Issue by jeynergil** [michaeldzjap/react-signature-pad-wrapper#66]
Warning: react-signature-pad-wrapper: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)

**Comment by MangelMaxime** [comment]
[Fixed documentation link](https://react.dev/warnings/special-props)

If I understand the documentation that I found only, the problem coming from

https://github.com/michaeldzjap/react-signature-pad-wrapper/blob/520593762b9aa9c3c696437d678dbc5b95050adc/src/SignaturePad.tsx#L11

I think `ref` is a reserved keyword in React world, and so libraries should not use it inside of their `props`. Following the exemple from the link above, I think `react-signature-pad-wrapper` should remove `ref` and use something like `canvasRef` because I think this is what the library is giving us access to.

**Comment by michaeldzjap** [comment]
@MangelMaxime I think removing the `ref` references from the `Props` type and `propTypes` would do the job, but then that would conflict with [this](https://github.com/michaeldzjap/react-signature-pad-wrapper/issues/62). So I am a bit confused about this... So (understandably) `ref` is a reserved _React_ keyword and shouldn't be referenced as a prop inside the component, but without it, it seems to result in a _TypeScript_ related compilation error.

**Comment by MangelMaxime** [comment]
@michaeldzjap I am also confused because I definitely saw libraries setting `ref` definition in their props.

And indeed, I remember this issue because if we don't expose `ref` in the props then users can't set it.

**Comment by MangelMaxime** [comment]
Hum, I am confused while trying to look into this issue I tried to remove `ref?: React.RefObject<SignaturePad>;` and `ref: PropTypes.object` and the code seems to still work and not report the error from #62.

I tried to understand where the `ref` definition comes in this case but following `React.PureComponent` implementation I was not able to understand how it was referenced...

However, while looking online for documentation I found that `React.PureComponent` is deprecated and React team encourage to use `function` now. Perhaps, making the conversion will fix the problem?

**Comment by michaeldzjap** [comment]
> However, while looking online for documentation I found that React.PureComponent is deprecated and React team encourage to use function now. Perhaps, making the conversion will fix the problem?

Well, not deprecated per se, but it is classified as "legacy" [now](https://react.dev/reference/react/legacy). I'm a bit hesitant to convert the class based code to function based code. I don't do a whole lot of _React_ development these days, so I'm not really familiar with (for me) more modern _React_ concepts like hooks. So its not that I am against it, but it would take time, which I don't have a whole lot of currently.

> Hum, I am confused while trying to look into this issue I tried to remove ref?: React.RefObject<SignaturePad>; and ref: PropTypes.object and the code seems to still work and not report the error from https://github.com/michaeldzjap/react-signature-pad-wrapper/issues/62.

So perhaps the "best" solution for now is to just remove them. I haven't been able to reproduce the error from #62 either.

**Comment by MangelMaxime** [comment]
> So perhaps the "best" solution for now is to just remove them. I haven't been able to reproduce the error from #62 either.

I guess so, I am sure I saw it happen today when loading the repo for the first time, but then I was not able to reproduce it. 

If #62, happens again and can be reproduced it can be revisited at that time I guess. 

My main issue with removing the `ref` is that projects that use the definition file to generate bindings for F#, ReScript, etc. will not be aware of the `ref` property. 

But this is a small edge case which is probably not worth having this warning in everyone projects.
