### ISSUE TITLE
Multiple signature-pads on the same page

### ISSUE THREAD

**Issue by viggis75** [michaeldzjap/react-signature-pad-wrapper#9]
Hi,

how can I make multiple signature-pads on the same page and being able to reference each of them individually?

I'm not sure how to extend the example here to take into account several instances of it:
 return <SignaturePad ref={ref => this.signaturePad = ref} />;

**Comment by michaeldzjap** [comment]
If you want multiple signature pads on the same page you'd have to render multiple `SignaturePad` components. And then just give each components a dedicated ref. Something like:

```javascript
...
render() {
    return (
        <Fragment>
            <SignaturePad ref={ref => this._firstSignaturePad = ref} />
            <SignaturePad ref={ref => this._secondSignaturePad = ref} />
        </Fragment>
    );
}
...
```

Then just reference the appropriate signature pad component by targeting the associated ref. Think that should answer your question, unless I misunderstood?

**Comment by viggis75** [comment]
Indeed, but at rendering time I don't know how many signatures I need since I want to render X number of orders that need a signature. Basically need to make SignaturePads dynamically

**Comment by michaeldzjap** [comment]
Then make your number of necessary signature pads a property or state variable, so that you can (re)render your signature pads. Something like:

```javascript
...
static propTypes = {
    numPads: PropTypes.number.isRequired
}

constructor(props) {
     this._signaturePad = new Map;
}
...
render() {
    return (
        <Fragment>
            {
                Array.from(Array(this.props.numPads), (x, i) => i).map(i => (
                    <SignaturePad ref={ref => this._signaturePad.set(i, ref)} />
                ))
            }
        </Fragment>
    );
}
```

By the way, happy to help, but this is more of a general _React_ question.
